name: Pull Request
description: Make a pull request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve our code!
  - type: textarea
    id: what-was-wrong
    attributes:
      label: What was wrong?
    validations:
      required: true
  - type: textarea
    id: how-was-it-fixed
    attributes:
      label: How was it fixed?
    validations:
      required: true
  - type: input
    id: related-to
    attributes:
      label: Issues this PR is related to
      value: "Related to Issue # "
    validations:
      required: false
  - type: input
    id: closes
    attributes:
      label: Issues this PR closes
      value: "Closes Issue # "
    validations:
      required: false
  - type: textarea
    id: cute-animal
    attributes:
      label: Cute animal photo
      description: Paste a picture of a cute animal in the box below
      value: "![Put a link to a cute animal picture inside the parenthesis-->]()"
    validations:
      required: false
