name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Version
      description: Which version of our software are you using?
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: py-version
    attributes:
      label: Python Version
      description: Which version of Python are you using?
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: osx/linux/win
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: cute-animal
    attributes:
      label: Cute animal photo
      description: Paste a picture of a cute animal in the box below
      value: "[Put a link to a cute animal picture inside the parenthesis-->]()"
    validations:
      required: true